export const GENERAL_MESSAGE = 'GLOBAL/GENERAL_MESSAGE';
export const GENERAL_ERROR = 'GLOBAL/GENERAL_ERROR';
export const CLEAR_GENERAL_MESSAGES = 'GLOBAL/CLEAR_GENERAL_MESSAGES';
export const GENERAL_LOADING = 'GLOBAL/GENERAL_LOADING';

export const REGISTER_MODAL_OPEN  = 'HEADER/REGISTER_MODAL_OPEN';
export const REGISTER_MODAL_CLOSE = 'HEADER/REGISTER_MODAL_CLOSE';

export const LOGIN_MODAL_OPEN  = 'HEADER/LOGIN_MODAL_OPEN';
export const LOGIN_MODAL_CLOSE = 'HEADER/LOGIN_MODAL_CLOSE';

export const LOGIN_USER_SUCCESS = 'USER/AUTH/LOGIN_USER_SUCCESS';
export const LOGIN_USER_PENDING = 'USER/AUTH/LOGIN_USER_PENDING';
export const LOGIN_USER_ERROR = 'USER/AUTH/LOGIN_USER_ERROR';
export const CLEAR_LOGIN_MESSAGES = 'USER/AUTH/CLEAR_LOGIN_MESSAGES';

export const REGISTER_USER_SUCCESS = 'USER/AUTH/REGISTER_USER_SUCCESS';
export const REGISTER_USER_PENDING = 'USER/AUTH/REGISTER_USER_PENDING';
export const REGISTER_USER_ERROR = 'USER/AUTH/REGISTER_USER_ERROR';
export const CLEAR_REGISTER_MESSAGES = 'USER/AUTH/CLEAR_REGISTER_MESSAGES';

export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';


export const USER_PROFILE_SUCCESS = 'USER/PROFILE/USER_PROFILE_SUCCESS';
export const USER_PROFILE_PENDING = 'USER/PROFILE/USER_PROFILE_PENDING';
export const USER_PROFILE_ERROR = 'USER/PROFILE/USER_PROFILE_ERROR';
export const CLEAR_USER_PROFILE_MESSAGES = 'USER/PROFILE/CLEAR_USER_PROFILE_MESSAGES';
export const USER_PROFILE_LOGOUT = 'USER/PROFILE/USER_PROFILE_LOGOUT';


export const CREATE_INGREDIENT = 'POST/INGREDIENT/CREATE_INGREDIENT';
export const EDIT_INGREDIENT = 'POST/INGREDIENT/EDIT_INGREDIENT';
export const UPDATE_INGREDIENT = 'POST/INGREDIENT/UPDATE_INGREDIENT';
export const DELETE_INGREDIENT = 'POST/INGREDIENT/DELETE_INGREDIENT';


export const CREATE_DIRECTION = 'POST/DIRECTION/CREATE_DIRECTION';
export const EDIT_DIRECTION = 'POST/DIRECTION/EDIT_DIRECTION';
export const UPDATE_DIRECTION = 'POST/DIRECTION/UPDATE_DIRECTION';
export const DELETE_DIRECTION = 'POST/DIRECTION/DELETE_DIRECTION';

export const UPDATE_DISHTYPE = 'POST/UPDATE_DISHTYPE';
export const UPDATE_DESCR = 'POST/UPDATE_DESCR';
export const UPDATE_FILES = 'POST/UPDATE_FILES';